### ISSUE TITLE
Sector converters required?

### ISSUE THREAD

**Issue by MaggotIISS** [inexorabletash/travellermap#128]
I saw somewhere (COTI maybe), someone mentioned needing a sector converter from ???? to ???? to assist with sector data for your site.  I am willing to try if you wish.  Tell me the filetypes and required output (T5SS?) and I will have a go Happily.  For the Emperor & Empire.

**Comment by inexorabletash** [comment]
Thanks for the inquiry. I can't recall a specific need here. Maybe someone wanted GAL (a ZIP with lots of sub-structure) ?
