### ISSUE TITLE
Booklet maker returns "Failed: Could not find file 'C:\home\site\wwwroot\api'."

### ISSUE THREAD

**Issue by markfaust-sri** [inexorabletash/travellermap#143]

**Comment by markfaust-sri** [comment]
Sorry if this is not the right way to submit an issue.  I tried to generate a booklet using several different sectors from the pull down, with several different output options, and I got the same error message each time.

**Comment by inexorabletash** [comment]
I'm seeing the issue. Not sure what's up. I'll debug tonight.

**Comment by inexorabletash** [comment]
Thanks - resolved in 083cee2a98803b2ef99d3f48108fee36e73be4cf
