### ISSUE TITLE
Add Mongoose Trade Codes

### ISSUE THREAD

**Issue by Grauenwolf** [inexorabletash/travellermap#154]
It appears that some Mongoose Traveller 2 trade codes are missing. Specifically High Technology, Low Technology, and Garden.

**Comment by inexorabletash** [comment]
These are somewhat documented at https://travellermap.com/doc/secondsurvey#remarks

Garden (`Ga`) is present in the T5SS data and should appear.

The `Ht`/`Lt` codes proposed by Mongoose haven't been incorporated into the T5SS; it's possible we could do that, but it's Marc Miller's call.

**Comment by Grauenwolf** [comment]
The person who told me may just have been mistaken about `Ga`. 

I've already patched the trade engine in TravellerTools to add any missing codes that we need, so this doesn't really affect me either way. So I'm happy with whatever direction you and Marc Miller decide.

**Comment by Grauenwolf** [comment]
P.S. Thanks for the link. That was interesting to read.
