### ISSUE TITLE
Data for Deepnight Revelation sector missing

### ISSUE THREAD

**Issue by CyberiaResurrection** [inexorabletash/travellermap#197]
When I clone out the repo, set it up, and run it up locally, it up and loses the plot, with "Could not find file ... \travellermap\res\Sectors\M1105\DeepnightRevelation.xml".

And lo, the file in question doesn't appear to be in repo HEAD as of this writing.

When I try to use the travellermap apis to get the data from www.travellermap.com:
- /data/Deepnight/tab returns a blank page
- /data/Deepnight/sec returns an empty .SEC file
- /data/Deepnight/metadata returns an apparently-valid XML file (according to both VS2017 and xmlvalidation.com).

Saving out the sec and xml files and re-running gives a _different_ blowup:
"There is an error in XML document (2,2)

Inner Exception:
InvalidOperationException: <Sector xmlns="> was not expected."

Contents of DeepnightRevelation.xml:
```
<?xml version="1.0"?>
<Sector xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" Tags="OTU" Abbreviation="Deep">
  <Name Source="Riftsedge Transit">Deepnight</Name>
  <X>-12</X>
  <Y>2</Y>
  <DataFile Milieu="M1105" />
  <Subsectors />
</Sector>
```

Contents of DeepnightRevelation.sec:
```
# Generated by https://travellermap.com
# 2020-07-12T22:16:32-07:00

# Deepnight
# -12,-2

# Name: Deepnight

# Milieu: M1105

# Subsector A: 
# Subsector B: 
# Subsector C: 
# Subsector D: 
# Subsector E: 
# Subsector F: 
# Subsector G: 
# Subsector H: 
# Subsector I: 
# Subsector J: 
# Subsector K: 
# Subsector L: 
# Subsector M: 
# Subsector N: 
# Subsector O: 
# Subsector P: 

# No world data available

```

**Comment by inexorabletash** [comment]
Whoops, sorry, fixed in 1c627610c2e156e49955d403c3d015d972e61c3a

**Comment by CyberiaResurrection** [comment]
Thanks for the quick turnaround.  Lemme grab your changes.

**Comment by CyberiaResurrection** [comment]
Yup, that comes up clean.
