### ISSUE TITLE
The SVG Poster Render Code does not generate usable SVG code

### ISSUE THREAD

**Issue by DaltonCalford** [inexorabletash/travellermap#202]
Although the svg generated works with Chrome, that is because chrome uses an earlier rendering standard.
I have found the resulting svg is troublesome with various editors but the easiest to test with is Inkscape.

inkscape.org

It's opensource and crossplatform.

The current travellermap poster map generator version uses a series of clippath/path which are expected to be closed elements by the renderer, but are specified as open paths (end point is not the start) so the rendering tool automatically closes the path with the default fill.

for example, here is sample code from the current svg poster output.

`<clipPath id="did3"><path d="M4.16667,-19.5l-0.333333,-0.5l0.333333,-0.5h0.666667l0.333333,-0.5h0.666667l0.333333,0.5h0.666667l0.333333,0.5h0.666667l0.333334,0.5h0.666666l0.333334,-0.5h0.666666l0.333334,0.5h0.666666l0.333334,0.5h0.666666l0.333334,-0.5h0.666666l0.333334,0.5h0.666666l0.333334,0.5l-0.333334,0.5l0.333334,0.5l-0.333334,0.5l0.333334,0.5l-0.333334,0.5l0.333334,0.5l-0.333334,0.5l0.333334,0.5h0.666666l0.333334,0.5l-0.333334,0.5l0.333334,0.5l-0.333334,0.5l0.333334,0.5l-0.333334,0.5h-0.666666l-0.333334,0.5h-0.666666l-0.333334,-0.5l0.333334,-0.5l-0.333334,-0.5h-0.666666l-0.333334,-0.5h-0.666666l-0.333334,0.5h-0.666666l-0.333334,0.5l0.333334,0.5l-0.333334,0.5l0.333334,0.5l-0.333334,0.5h-0.666666l-0.333334,-0.5l0.333334,-0.5l-0.333334,-0.5h-0.666666l-0.333334,-0.5h-0.666667l-0.333333,-0.5l0.333333,-0.5l-0.333333,-0.5l0.333333,-0.5l-0.333333,-0.5l0.333333,-0.5l-0.333333,-0.5l0.333333,-0.5l-0.333333,-0.5l0.333333,-0.5l-0.333333,-0.5l0.333333,-0.5l-0.333333,-0.5l0.333333,-0.5l-0.333333,-0.5h-0.666667l-0.333333,-0.5h-0.666667l-0.333333,0.5h-0.666667Z"/></clipPath>`

Whereas here is a better method with less work and more accuracy

```
<path
       sodipodi:type="star"
       style="fill:none;fill-rule:evenodd;stroke:#ff0000;stroke-width:0.0226082;stroke-linecap:round;stroke-linejoin:round;paint-order:fill markers stroke"
       id="path2382"
       sodipodi:sides="6"
       sodipodi:cx="9.4044283"
       sodipodi:cy="11.132132"
       sodipodi:r1="7.0027518"
       sodipodi:r2="8.2935858"
       sodipodi:arg1="2.0942812"
       sodipodi:arg2="2.6178799"
       inkscape:flatsided="true"
       inkscape:rounded="0"
       inkscape:randomized="0"
       d="M 5.9037434,17.197091 2.4016767,11.132929 5.9023618,5.0679695 12.905114,5.0671718 16.40718,11.131334 12.906495,17.196294 Z" />
```
I am attaching a screenshot as an example.

![image](https://user-images.githubusercontent.com/4127055/97480266-8b847780-1929-11eb-94a9-bd4af5729026.png)

**Comment by inexorabletash** [comment]
> The current travellermap poster map generator version uses a series of clippath/path which are expected to be closed elements by the renderer, but are specified as open paths (end point is not the start) so the rendering tool automatically closes the path with the default fill.

The SVG generation was relying on `fill="none"` being inherited, but that was incorrect. Fixed that, which improves things but there are still issues with the clip path I need to figure out...

![image](https://user-images.githubusercontent.com/771547/97511815-35bdc880-1945-11eb-95da-804ceb99993c.png)

**Comment by inexorabletash** [comment]
> The current travellermap poster map generator version uses a series of clippath/path which are expected to be closed elements by the renderer, but are specified as open paths (end point is not the start) so the rendering tool automatically closes the path with the default fill.

The clipPaths are all closed (paths end with `Z` command), so your comment seems incorrect...
 
> Whereas here is a better method with less work and more accuracy

This comment doesn't provide much guidance, since it's describing different content. I can't discern what's "better", "less work", or what "more accuracy" mean in this context.

The SVG code generation is here if you want to take a look and make any suggestions:

https://github.com/inexorabletash/travellermap/blob/main/server/graphics/SVGGraphics.cs



> 
> ```
> <path
>        sodipodi:type="star"
>        style="fill:none;fill-rule:evenodd;stroke:#ff0000;stroke-width:0.0226082;stroke-linecap:round;stroke-linejoin:round;paint-order:fill markers stroke"
>        id="path2382"
>        sodipodi:sides="6"
>        sodipodi:cx="9.4044283"
>        sodipodi:cy="11.132132"
>        sodipodi:r1="7.0027518"
>        sodipodi:r2="8.2935858"
>        sodipodi:arg1="2.0942812"
>        sodipodi:arg2="2.6178799"
>        inkscape:flatsided="true"
>        inkscape:rounded="0"
>        inkscape:randomized="0"
>        d="M 5.9037434,17.197091 2.4016767,11.132929 5.9023618,5.0679695 12.905114,5.0671718 16.40718,11.131334 12.906495,17.196294 Z" />
> ```
> 
> I am attaching a screenshot as an example.
> 
> ![image](https://user-images.githubusercontent.com/4127055/97480266-8b847780-1929-11eb-94a9-bd4af5729026.png)

**Comment by inexorabletash** [comment]
Appears to be that Inkscape doesn't support `rgba()` colors:

https://gitlab.com/inkscape/inbox/-/issues/1195

**Comment by inexorabletash** [comment]
... which can be worked around by changing the serialization to use `stroke-opacity` and `fill-opacity` instead.

**Comment by inexorabletash** [comment]
Yep, that did it:

![image](https://user-images.githubusercontent.com/771547/97519253-2dba5480-1956-11eb-9ae2-14f8ade91f9b.png)
