### ISSUE TITLE
(minor) is used to denote multiple natives

### ISSUE THREAD

**Issue by BackworldTraveller** [inexorabletash/travellermap#207]
The name (minor) is used multiple times to denote an anonymous minor race. This should be named using some unique ID (e.g. Planet Name)

e.g. Present 4 times in Spinward Marches

**Comment by tjoneslo** [comment]
I have a preference for leaving the unnamed, un-described, minor races as "(minor)", as an indicator there is no information anywhere about them.

**Comment by BackworldTraveller** [comment]
Actually we have been over this on the mailing list...So we just need to update the names as agreed there.
1305 - Nakege (minor)
1511 - Tionale: (Sixes)
3019 - 457-973: (Pelosians)
0240 - 769-422: (Lothloriens)

**Comment by inexorabletash** [comment]
T5SS data (M1105 Official or In Review) should be discussed on the mailing list. This repo only has a copy of the data, and is not the canonical source.
