### ISSUE TITLE
Stellar data in different order across M1105 and M1201

### ISSUE THREAD

**Issue by lawsonj2019** [inexorabletash/travellermap#228]
I have been looking at some of the stellar data within the source files with the intent on writing a small system generation script. One of the areas I've noticed is that in some cases there are differences in the order of the stars in the data across the different mileu. Is this intentional or has a reason behind it?

An example is below for Capella in the Solomani Rim. M1201 appears to be "more correct" if you look up Capella as a real star system.  For M1105 it is listed with the G0 III first, whereas M1201 it is G8 III.

https://github.com/inexorabletash/travellermap/blob/18b656079a5fb3ec6be779c7f4309f9c86d865e2/res/Sectors/M1105/Solomani%20Rim.tab#L177

https://github.com/inexorabletash/travellermap/blob/18b656079a5fb3ec6be779c7f4309f9c86d865e2/res/Sectors/M1201/Solomani%20Rim.tab#L177

The stellar order also seems to have been moved around in the https://github.com/inexorabletash/travellermap/commit/a55657d37c778fc33b52610692016b6acd43a60e commit. For example, Algol in the Aldebaran sector changed from `A5V B8V K2IV` to `K2IV A5V B8V`. Are the two inconsistencies connected?

I'm not looking for any changes - just clarification, please.

**Comment by inexorabletash** [comment]
Only the 1105 data has been carefully scrutinized and fixed. Other milieu is from older publications and may differ wildly. There has not (yet) been an effort to reconcile.

**Comment by lawsonj2019** [comment]
Thanks for the clarification.
