### ISSUE TITLE
Link to TravellerWorlds doesn't generate a world

### ISSUE THREAD

**Issue by arctellion** [inexorabletash/travellermap#230]
I don't know if this counts as an issue for TravellerMap or for the sister site TravellerWorlds.

The link in the pop-up box on the left hand side called 'Generate World Map', which links to TravellerWorlds, is no longer generating a world map. This may be as a result of api changes at TravellerWorlds end, but the generated link doesn't work at present, it gets to TravellerWorlds then sits just saying Rendering...

**Comment by inexorabletash** [comment]
Known issue, the maintainer of that site is working on it.

**Comment by inexorabletash** [comment]
TW maintainer indicates this should now be fixed.
