### ISSUE TITLE
remove linefeeds in raw data

### ISSUE THREAD

**Issue by pmoule** [inexorabletash/travellermap#236]
Hi Joshua

In some sector files special characters for linefeed `&#x0a;` are contained.
Mostly files in `res/Sectors/Distant Fringe` but also in other files below `res` folder.
These can be also found when information is requested via your API e.g.
https://travellermap.com/api/sec?sector=Halcyon&type=SecondSurvey&milieu=M1105 (Allegiance section)

I'm processing allegiance information contained in these surveys for having consistent allegiance information over all sectors for each milieu. I can filter these for processing the sector files, so no real issue.

My question is, are these linefeeds intended? Maybe for label rendering in your map?
If not, these can be removed. I can offer to remove these and make a PR then.

Best wishes
Patrick

**Comment by inexorabletash** [comment]
Thanks, fixed.

**Comment by inexorabletash** [comment]
It should only be a problem if used in Allegiance declarations. In those cases the author should have provided a simple string, and used explicit labels or wrapping options instead.

In explicit labels the LF entities are allowed/expected.

**Comment by pmoule** [comment]
Great, thanks!
