### ISSUE TITLE
M1105 Storr sector - incomplete allegiance metadata

### ISSUE THREAD

**Issue by pmoule** [inexorabletash/travellermap#245]
Sector data of Storr sector contains allegiance codes `Ar`, `Bp`, `Ou`, `Mr`, `Su `and `Ge`.
These are not visible as allegiances in sector's metadata even thoug allegiances are describes in related sector xml files.

Files: 
https://github.com/inexorabletash/travellermap/blob/main/res/Sectors/M1105/Storr.tab
https://github.com/inexorabletash/travellermap/blob/main/res/Sectors/M1105/Storr.xml#L33-L38

Reason for this behaviour is that
1. codes are not known in àllegiance_code_tab` 
2. https://github.com/inexorabletash/travellermap/blob/main/server/Sector.cs#L142 only compares for `Code`attribute in xml

There are two  possible approaches for solving this issue.
1. Replace 2-letter codes by 4-letter codes in `Storr.tab` (simple approach)
2. refine `Sector.cs` to compare codes with `Code`and `Base` attributes (not recommended, because base is not unique)

**Comment by inexorabletash** [comment]
Only allegiances in the T5SS "official" data get 4-character codes; this was a case where the sector author had added custom codes, I asked them to revert to 2-character codes, but I didn't double check that the metadata was updated as well. Thanks for catching!

**Comment by pmoule** [comment]
ok, thanks for your commit. Wouldn't that mean to use 2-char codes also for borders in xml?
see https://github.com/inexorabletash/travellermap/blob/main/res/Sectors/M1105/Storr.xml#L45-L58

**Comment by inexorabletash** [comment]
Yes, thanks! Good catch.

**Comment by inexorabletash** [comment]
Overall I should have more consistency checking; the site evolved from using very messy inconsistent data to having the T5SS dataset included and more and more rigor, but lacks the checks it should have to ensure no new problems are introduced.
