### ISSUE TITLE
Jump Route's are not shortest paths

### ISSUE THREAD

**Issue by MarkStewart2** [inexorabletash/travellermap#253]
I ran across a case where the path from A to B required more jumps than B to A. 

Vincennes -> Dpres at jump 2 (no restrictions) is 68 parsecs 36 jumps
Dpres -> Vincennes at jump 2 (no restrictions) is 70 parsecs 37 jumps

**Comment by inexorabletash** [comment]
Thanks for the report. A couple of guesses:

* The "cost" is calculated as Euclidean distance between a node and the destination. This is not the same as Hex distance, which could disrupt the algorithm. IIRC, this was an intentional choice 
* The "cost" doesn't consider the number of jumps, just how efficiently (per the above metric) the path gets to the destination.

I suspect that under some combination of the above heuristics the paths are equivalent, even though they're quite obviously not in terms of number of jumps.

**Comment by inexorabletash** [comment]
A better cost metric might be one of:

* Number of jumps so far + (hex distance to destination / jump rating)
* Number of jumps so far + (euclidean distance to destination / jump rating)

The former might converge faster, but the latter might give better results.

**Comment by MarkStewart2** [comment]
Would you prefer a result that was least hops (assuming it was fast)?

**Comment by inexorabletash** [comment]
Yes. I'm sure tweaks to the A* implementation will do it, I just need to find the time and attention span. On Apr 4, 2023, at 9:58 PM, Mark Stewart ***@***.***> wrote:﻿
Would you prefer a result that was least hops (assuming it was fast)?

**Comment by inexorabletash** [comment]
LOL... I spent an hour and reimplemented A* following https://en.wikipedia.org/wiki/A*_search_algorithm and... not only does the asymmetric path problem reoccur, I'm getting longer routes! (70/73 parsecs, 37/38 jumps)

Hmmm....

**Comment by inexorabletash** [comment]
Whoops, that was a bug. Okay, now it's symmetric for several test cases (yay) but Vincennes<->Dpres is 70 parsecs/36 jumps. So... what's different?

**Comment by inexorabletash** [comment]
Oh, that's okay - longer distance in parsecs is fine, it's the jumps that's the important thing.

Except for fuel, which is an extra heuristic. Total number of jumps is most important, but parsecs covered is secondary. So need to weigh that in.

**Comment by inexorabletash** [comment]
Should be better now - cost estimate is _hex_distance / jump_rating_ and edge cost is _1 + (hex_distance / 36)_ so it biases towards minimizing jump count first but also tries to minimize number of parsecs.

Vincennes &larr;&rarr; Dpres is symmetric now, 67 parsecs, 36 jumps.

**Comment by MarkStewart2** [comment]
Cool - I've not stumbled across any more defects
