### ISSUE TITLE
Unable to click/tap to open system data on mobile

### ISSUE THREAD

**Issue by ErroneousBosch** [inexorabletash/travellermap#328]
Tried on Android Chrome, tapping and dragging, pinch zoom, etc all work, but tapping on a system has no effect. Tried long pressing, tried it in app mode, etc. Nothing seems to work.

**Comment by inexorabletash** [comment]
When you say "system data", are you referring to the panel at the bottom of the screen as shown below, or something else?

![image](https://github.com/inexorabletash/travellermap/assets/771547/44febc65-5176-4ede-acf6-4506eed2b942)

**Comment by ckennedy666** [comment]
I've seen similar. The only way I can get the system pop up at the bottom of the screen is by searching for the system. Tapping didn't work on Android 13 using Edge.

**Comment by ErroneousBosch** [comment]
> When you say "system data", are you referring to the panel at the bottom of the screen as shown below, or something else?
> 
> ![image](https://user-images.githubusercontent.com/771547/257017903-44febc65-5176-4ede-acf6-4506eed2b942.png)

Yes, this is what I am referring to. We tried on a Samsung tablet and my pixel phone, both on Android 13.

One correction, just verified it *does* work on iOS, my mistake.

**Comment by inexorabletash** [comment]
Thanks. I'll give it a whirl on Android and see what's up.

**Comment by ErroneousBosch** [comment]
Cool, let me know if I can help or test. I'm not a C# person, but I can at least test.

**Comment by inexorabletash** [comment]
The client side is all HTML/JS. Likely there was a browser engine change in how touch events (used for dragging) relate to click events (used for highlighting) that I need to work around. Or maybe I was relying on what is considered a browser bug.

**Comment by inexorabletash** [comment]
Or possibly 4cb1eb3d31e57be3f723a3e4a31ea8b634b1c76f broke something, if the failure is recent.

**Comment by inexorabletash** [comment]
I pushed a change to the server that might have fixed it - tapping works fine on my partner's Android phone. Can you reload and try again?

**Comment by ErroneousBosch** [comment]
The information is coming up! Thank you for the awesome quick response. Pic is from my Samsung Galaxy Tab S5 Lite in Chrome.

![Screenshot_20230730_124029_Chrome](https://github.com/inexorabletash/travellermap/assets/20829218/b228dcc4-5d1f-462c-b65f-d56b150a3451)

**Comment by inexorabletash** [comment]
Great! The issue was what I'm guessing is a browser change where a single touchstart/touchend with no move now is sent a touchstart/touchmove/touchend sequence with no actual movement. I just needed to improve the logic to handle that.

**Comment by inexorabletash** [comment]
Fixed by b86922f2042ee0251645379df52cf0b6fc50fa1f
