### ISSUE TITLE
Cannot access 'searchRequest' before initialization

### ISSUE THREAD

**Issue by samuelpenn** [inexorabletash/travellermap#329]
Not sure if this is a bug in TravellerMap, or something has changed which I need to take account of.

I wrote the FoundryVTT plugin for TravellerMap, which allows routes to be displayed in an inline map. I've noticed that when trying to display a map with a route, I now get the following error in the browser console:

```
index.js?update=2023-07-08T08:29:10:1247 Uncaught (in promise) ReferenceError: Cannot access 'searchRequest' before initialization
    at search (index.js?update=2023-07-08T08:29:10:1247:5)
    at index.js?update=2023-07-08T08:29:10:874:7
    at Array.forEach (<anonymous>)
    at index.js?update=2023-07-08T08:29:10:871:15
    at index.js?update=2023-07-08T08:29:10:1689:3
```

Not sure when this problem started happening. The type of URL request that I am making is this:
```
https://travellermap.com/?qr=%7B%22Tour%22%3Atrue%2C%22Route%22%3Atrue%2C%22Results%22%3A%7B%22Items%22%3A%5B%7B%22World%22%3A%7B%22Name%22%3A%22Tobia%22%2C%22SectorX%22%3A-4%2C%22SectorY%22%3A0%2C%22HexX%22%3A32%2C%22HexY%22%3A15%7D%7D%2C%7B%22World%22%3A%7B%22Name%22%3A%22Attee%22%2C%22SectorX%22%3A-4%2C%22SectorY%22%3A0%2C%22HexX%22%3A31%2C%22HexY%22%3A16%7D%7D%2C%7B%22World%22%3A%7B%22Name%22%3A%22Imisaa%22%2C%22SectorX%22%3A-4%2C%22SectorY%22%3A0%2C%22HexX%22%3A29%2C%22HexY%22%3A16%7D%7D%5D%7D%7D
```
I notice that I get the same searchRequest console error when clicking the 'Grand Tour' easter egg from the /doc/about page, which makes me think it's something changed in TravellerMap.

**Comment by inexorabletash** [comment]
Bug in the script introduced in 6109bb523f5b12173cd2830576f20f3c23bdf07c

Try now? I put up a quick fix, will commit it later.

**Comment by samuelpenn** [comment]
Can confirm it's working, thanks.
