### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by Grauenwolf** [inexorabletash/travellermap#392]
I downloaded the repo yesterday and noticed that several files were missing from source control. For example, `\res\Sectors\M1105\banners.sec`.

Likewise, some files exist but aren't part of the project such as `\res\Sectors\milieu.tab`.

I am able to run locally, but these prevented me from publishing to Azure.

**Comment by inexorabletash** [comment]
This seems specific to the VS project; file that are currently in use are in the repo. I don't currently use the VS project for deployments. If you just sync the VS project with the actual files that may solve your problem.

**Comment by inexorabletash** [comment]
PRs welcome for anything else that's missing, or close this when it looks good to you.
