### ISSUE TITLE
Search isn't working when running locally

### ISSUE THREAD

**Issue by Grauenwolf** [inexorabletash/travellermap#393]
When I run locally, I get this error message.

URL: http://localhost:50103/api/search?q=Glisten
Message: Format of the initialization string does not conform to specification starting at index 0.

**Comment by inexorabletash** [comment]
You followed all the instructions at https://github.com/inexorabletash/travellermap/blob/main/SETUP.md#to-add-a-database ?

Did the reindex action succeed?

**Comment by Grauenwolf** [comment]
Nope, I was still on the "Trying it out" step.

**Comment by inexorabletash** [comment]
Let me know if it works after those steps. And we should update the docs to mention "try it... except for search (see below)" 😀
