### ISSUE TITLE
Tyr TR 1518 links to wrong wiki page

### ISSUE THREAD

**Issue by CaptainNomouth** [inexorabletash/travellermap#431]
The wiki link for Tyr in the Dpres subsector of the Trojan Reach (1518) links to a wiki page for a different Tyr: 
https://wiki.travellerrpg.com/Tyr_(world)

Should be:
https://wiki.travellerrpg.com/Tyr_(TR_1518)_(world)

**Comment by inexorabletash** [comment]
The links to the wiki are autogenerated, currently just using the world name, so this is a problem for any duplicates.

If the wiki can support passing the sector/hex along in the URL and deduplicate on its side, that would be ideal. I've asked the wiki experts.

**Comment by inexorabletash** [comment]
On the wiki, the first link has been updated to be a disambiguating page, which is the current least-bad solution.
