### ISSUE TITLE
Feature Request: A way to measure 'real-space'/cartesian distance between two hexes

### ISSUE THREAD

**Issue by GabrielGABFonseca** [inexorabletash/travellermap#499]
The route plotter, as it stands, already showcases the total Parsecs travelled for the calculated route, which for high jump numbers will usually coincide with the actual distance between the two hexes. But for systems with rifts between them (such as, for instance, Vland and Regina), this workaround does not work.

Some alternative means to measure the distance between two systems (or better yet, between any two arbitrary hexes) would be a low-priority, but welcome addition.

**Comment by inexorabletash** [comment]
You can try https://travellermap.com/tools/distance

It is not integrated into the map, though.

**Comment by GabrielGABFonseca** [comment]
This is exactly what I needed! A shame it isn't somewhere more visible. I've bookmarked it for my own use, but perhaps it could be added as a link to the "Experimental Features" tab of the Options menu?

In any case, thank you for your help!
