### ISSUE TITLE
Importance calculation does not cope with non-Imperium bases.

### ISSUE THREAD

**Issue by mmarquee** [inexorabletash/travellermap#51]
The T5 calculation of importance doesn't count Hiver and K'kree based - I assume others as well, this means the Federation world's LOOK less important than some nearby world's outside of Federation.

**Comment by inexorabletash** [comment]
Can you give me some examples?

The calculation I have in https://github.com/inexorabletash/travellermap/blob/master/server/SecondSurvey.cs#L547 does account for this, but that isn't used if the data has {Ix} already.

**Comment by mmarquee** [comment]
I think it might actually be the way in which the data is stored - if you look at the sectors that are stored as .tab files (for example Langere), then they have some Hiver worlds that have double military bases, where as what I generated as .sec don't. As a specific example Langere itself has an importance of 5 - which is higher than almost every other Hiver world - and it has bases 'KM', so military and naval bases, which is represented as a 'F' in .sec mode. Maybe it is my data that is off.

**Comment by mmarquee** [comment]
As this appears to be the Hivers own problem, I'll close the issue.
