### ISSUE TITLE
Add M1202 (TNE) sectors

### ISSUE THREAD

**Issue by mmarquee** [inexorabletash/travellermap#74]
There are maps available for M1201 (and indeed M1117 & M1120 (Dark Times)) - dual listings, etc. I am looking at the M1201/2 stuff that is in the Regency Handbook. Not sure how to cope with partial sectors (i.e. much of TNE is subsectors rather that full sectors)

**Comment by inexorabletash** [comment]
I thought TNE was 1202 not 1201? Anyway...

Easiest thing to do would be to add placeholder entries (empty name, uwp: `???????-?`, pbg: `???`, allegiance: `??`) for worlds in the other subsectors based on M1105 . That's what the site does behind the scenes for missing _sectors_ in alternate milieux, at least for rendering.

**Comment by inexorabletash** [comment]
What sectors do we have published data for? (let's make a checklist)

**Comment by mmarquee** [comment]
Corrected title

**Comment by mmarquee** [comment]
TNE Rules (1117):
Old Expanses (Subsector M)
Diaspora (Subsector P)
Spinward Marches (Subsector C) - with trade routes 

Regency Sourcebook (Dual Listed 1117?/1202):
Spinward Marches (Subsectosr A-P)
Deneb (Subsectors A-P)
Trojan Reach (Subsectors C,D,G,H)
Reft (Subsectors A,B,C,E,F,G,I,K

**Comment by mmarquee** [comment]
As for Challenge magazine, these are all I have :

Challenge 71:
Lishun (Subsector L)
Challenge ?5:
Zarushagar (Subsector K,L)
Challenge 76:
Diaspora (Subsector C)

**Comment by mmarquee** [comment]
Progress as of 28/09:

- Borders for Spinward Marches done. 
- Zarushagar K & L borders and UWPs
- Lishun L borders and UWPs
- Starting Massilia A

**Comment by inexorabletash** [comment]
In case you weren't aware of the tool: /borders/regen.htm?sector=_name_&milieu=_token_ will generate borders taking adjacent sectors into account.

I'll take a look in my materials and see if I can spot any others.

**Comment by mmarquee** [comment]
I have found that Traveller Chronicles has a TNE era map for Solomani Rim, which seems plausible. The TME rulebook shows some other pockets to rimward for Old Expanses, but no other details. I have extrapolated the the borders of the Aslan Hierate in Trojan Reach as it is not fully shown in Regency Sourcebook. 
_All_ I need to do now is check Spinward Marches and Solomani Rim UWPs - and sort out some new base codes.

**Comment by mmarquee** [comment]
The later 1264 stuff from the second FFE CD-ROM has 2 further TNE adventures, which also have some maps, so I will have a look at these as well.

**Comment by Nathan-Brazil** [comment]
Hi there, If you have the TNE CD-ROM 2, you will want to check and compare the history of the Rim comparing the Traveller Chronicle Children of Earth issues which is wonderfully detailed but not canon (oh that dreaded word), vs the lack of map detail and canon (but, oh so badly edited).  Basically the religious, psionic friendly Republic of Terra of Chronicle, vs the Virus/Cym friendly Terran Confederation of 1248.

**Comment by mmarquee** [comment]
OK, I think I've done as much as I can. Stuff from TNE Rulebook, Regency Sourcebook,  TNE Deluxe RCES Briefing, various Challenges, Traveller Chronicle (Solomani Rim), Opal and Zhodhani Base (for Vland). Having looked at the M1248 sourcebooks, I am not sure of the canonicity (if that is a word) of Vland, as it seems to not match the description of nearly a sector wide region. Also nothing in Usdiki, which seems also not to match.
I also extrapolated the Reform Coalition Area of Operation into Solomani Rim, Old Expanses and Alpha Crucis.

**Comment by mmarquee** [comment]
From "Out of the Darkness" -- "By the mid 1190s, the Federation was weak but stable, covering two-thirds of Gushemege and growing steadily" ... "By 1185, the New Ziru Sirka had almost pushed its borders out as far as the boundaries of Vland Sector, and ten years after that it had regained nearly every system it had controlled in the Rebellion period." .. "From 1200 onwards, the United Worlds controlled a small cluster of worlds but its reputation as a safe port for Free Traders made it a center for commerce."

Not sure how to reflect these in the M120x maps as it does reflect the maps in TNE ruleset - any idea which is now canon (or at least most canon)?

**Comment by Nathan-Brazil** [comment]
RE: Your 1201 project.  If I may I am doing the 1248 mapping.  Reference that for eventual borders if it is suitable for your needs.  Besides the 10.5 sectors found in the other books, I am only putting up the borders.  I threw the out of darkness map into Paint and sliced up the map into "hex" sized slices to draw the 1248 borders accurately (as far as the map is drawn anyways in the xml files)
- Usdiki and the 4th Imperium do not become a factor until 1220 so maps in 1201 may not have a full empire and that is ok.  
- Vland's 1248 borders may not have correlation to 1201 borders.  They did the Capital Bid, then got whomped on during the Scouring of Vland.  Both occurred after 1201.  Their borders may have expanded to the limits of the Black Curtain, then shrunk somewhat after the Scouring, then expanded or modified to 1248 borders.

**Comment by Nathan-Brazil** [comment]
I am putting up the next set of 1248 borders now.  They may be informative.

**Comment by mmarquee** [comment]
Suggestion via email:
"There was one reference I did not see Mark Humphrys mention in his github note the other day.  Paranoia Press published New Era Updates for The Beyond and Vanguard Reaches Sectors.  They are available on the defunct website here http://web.archive.org/web/19970730073206/http://www.inlink.com/~scoundrl/paranoia.htm.  These should be as valid as other fan-based sector maps.  Please forward to Mark if he did not know and as I do not have his email."

I've looked at the data and it will take some time to reconcile it against what is already in the Beyond and Vanguard Reaches in travellermap data - it looks like it's gone through several reviews and although it is largely OK, the mapping between the 2 sets of data is not 1:1

**Comment by mmarquee** [comment]
Have pushed the majority of the changes to the main branch, and they've been merged. Some issues fed back from Joshua:

And here's the admin/codes?milieu=M1201 output:
(Grkaadudgaagii)W - Alpha Crucis [M1201] 
(Ojehshodu)W - Corridor [M1201] 
Ad - Alpha Crucis [M1201] 
B:E - Reaver's Deep [M1201] 
BrinW - Corridor [M1201] 
CM - Hinterworlds [M1201] 
fl - Old Expanses [M1201] 
HI - Solomani Rim [M1201] 
IC - Spinward Marches [M1201] 
Kkre0 - Spinward Marches [M1201] 
L:1011 - Spinward Marches [M1201] 
Li - Lishun [M1201] 
NI - Reft Sector [M1201] 
NiCm - Solomani Rim [M1201] 
No - Spinward Marches [M1201] 
O: - Trojan Reach [M1201] 
Ow - Hinterworlds [M1201] 
R:G - Zarushagar [M1201] 
Rp - Reaver's Deep [M1201] 
RsC - Deneb [M1201] 
Rw0 - Deneb [M1201] 
Rw1 - Deneb [M1201] 
Rw5 - Deneb [M1201] 
RwV - Deneb [M1201] 
RwZ - Deneb [M1201] Spinward Marches [M1201] 
RwZ] - Spinward Marches [M1201] 
Rz2 - Deneb [M1201] 
V - Corridor [M1201] 

Some of these are typos, some need to be added - Refugee World for example.

**Comment by mmarquee** [comment]
I think that is basically done now, I can't find any other data to mine for extrapolation
